# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventBetDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BetInfoDialog(object):
    def setupUi(self, BetInfoDialog):
        BetInfoDialog.setObjectName("BetInfoDialog")
        BetInfoDialog.resize(600, 347)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./media/IconaFrontEnd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BetInfoDialog.setWindowIcon(icon)
        self.BetInfo_labelTitolo = QtWidgets.QLabel(BetInfoDialog)
        self.BetInfo_labelTitolo.setGeometry(QtCore.QRect(0, 0, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.BetInfo_labelTitolo.setFont(font)
        self.BetInfo_labelTitolo.setObjectName("BetInfo_labelTitolo")
        self.BetInfo_tbl = QtWidgets.QTableWidget(BetInfoDialog)
        self.BetInfo_tbl.setGeometry(QtCore.QRect(0, 30, 600, 300))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BetInfo_tbl.setFont(font)
        self.BetInfo_tbl.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.BetInfo_tbl.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.BetInfo_tbl.setColumnCount(4)
        self.BetInfo_tbl.setObjectName("BetInfo_tbl")
        self.BetInfo_tbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.BetInfo_tbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BetInfo_tbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BetInfo_tbl.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BetInfo_tbl.setHorizontalHeaderItem(3, item)
        self.BetInfo_tbl.horizontalHeader().setDefaultSectionSize(149)
        self.BetInfo_tbl.verticalHeader().setVisible(False)

        self.retranslateUi(BetInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(BetInfoDialog)

    def retranslateUi(self, BetInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        BetInfoDialog.setWindowTitle(_translate("BetInfoDialog", "Events Info"))
        self.BetInfo_labelTitolo.setText(_translate("BetInfoDialog", "Informazioni Scommessa"))
        item = self.BetInfo_tbl.horizontalHeaderItem(0)
        item.setText(_translate("BetInfoDialog", "Id Evento"))
        item = self.BetInfo_tbl.horizontalHeaderItem(1)
        item.setText(_translate("BetInfoDialog", "Nome Evento"))
        item = self.BetInfo_tbl.horizontalHeaderItem(2)
        item.setText(_translate("BetInfoDialog", "Quota"))
        item = self.BetInfo_tbl.horizontalHeaderItem(3)
        item.setText(_translate("BetInfoDialog", "Esito Scelto"))
